[[headers]]
  for = "/.netlify/functions/get-top-occurrences"
  [headers.values]
    Access-Control-Allow-Origin = "https://sistema-envios-nuvem.pages.dev"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
